spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: always

logging:
  level:
    root: debug
    org.hibernate.type: trace